---
# handlers for ivansible.srv_redis

- name: restart redis service
  systemd:
    name: redis-server
    state: restarted
  become: true

- name: restart redis stunnel service
  systemd:
    name: redis-stunnel
    state: restarted
  become: true
...
